sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRSrCtJCn3gicN18qbn
    access-key-secret: Axr6qrlzFIjO3FOQqnuqvoeQFa8SlF
    bucket-name: sky-take-out-cwj333
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
