sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  dev-alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFCoQeyF4kTEax5yxtX
    access-key-secret: 3xjBNfIPeeGXrinc0U6yQ5Vp8xhKPd
    bucket-name: sky-take-out-wb333
  redis:
    host: localhost
    port: 6379
    password: 123456
#    url: redis://000000@127.0.0.1:6379
#    指定使用Redis的哪个数据库，Redis服务启动后默认有16个数据库，编号分别是从0到15，即DB0到DB15
    database: 0

