sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  dev-alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFCoQeyF4kTEax5yxtX
    access-key-secret: 3xjBNfIPeeGXrinc0U6yQ5Vp8xhKPd
    bucket-name: sky-take-out-wb333

