server:
  port: 8084

spring:
  # 配置多个MySQL数据源
  datasource:
    item:
      driver-class-name: ${sky.datasource.item.driver-class-name}
      jdbc-url: jdbc:mysql://${sky.datasource.item.host}:${sky.datasource.item.port}/${sky.datasource.item.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.item.username}
      password: ${sky.datasource.item.password}
      type: com.alibaba.druid.pool.DruidDataSource

    order:
      driver-class-name: ${sky.datasource.order.driver-class-name}
      jdbc-url: jdbc:mysql://${sky.datasource.order.host}:${sky.datasource.order.port}/${sky.datasource.order.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.order.username}
      password: ${sky.datasource.order.password}
      type: com.alibaba.druid.pool.DruidDataSource

    user:
      driver-class-name: ${sky.datasource.user.driver-class-name}
      jdbc-url: jdbc:mysql://${sky.datasource.user.host}:${sky.datasource.user.port}/${sky.datasource.user.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.user.username}
      password: ${sky.datasource.user.password}
      type: com.alibaba.druid.pool.DruidDataSource

    default:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${sky.datasource.default.host}:${sky.datasource.default.port}/${sky.datasource.default.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.default.username}
      password: ${sky.datasource.default.password}
      type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #  比如你的配置是 typeAliasesPackage: com.sky.entity。
  #  这意味着 MyBatis 会扫描指定的包路径 com.sky.entity，并将这个包中的所有实体类注册为别名，
  #  注册后你就可以在 MyBatis 的映射文件（.xml）中直接使用实体类的类名而不需要写全路径的类名。
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true


sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${sky.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: ${sky.jwt.admin-ttl}
    # 设置前端传递过来的令牌名称
    admin-token-name: ${sky.jwt.admin-token-name}