server:
  port: 8086
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # sentinel的控制台地址
      http-method-specify: true # 是否设置请求方式作为资源名称

